name: chewie_video_demo_corner
description: video player chewie 라이브러리 테스트
version: 1.0.1
homepage: https://github.com/eight-corner/flutter_test

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  chewie:
  video_player:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  very_good_analysis: ^3.0.0

flutter:
  uses-material-design: true

assets:
  - assets/videos/ive.mp4
  - assets/videos/instagram_video.mp4
